# Jenkins Kubernetes Secrets
# These secrets must exist in the oms-cicd namespace before deploying Jenkins.
# They are referenced by the Helm values via additionalExistingSecrets + JCasC.
#
# IMPORTANT: Do NOT commit actual secret values to this file.
# This file documents the required secrets and how to create them.

# --- GitHub Credentials ---
# Used by Jenkins to clone the saddle-oms repository.
#
# Create:
#   kubectl create secret generic github-credentials \
#     -n oms-cicd \
#     --from-literal=username=<github-username> \
#     --from-literal=password=<github-personal-access-token>
#
#   kubectl label secret github-credentials -n oms-cicd \
#     "jenkins.io/credentials-type=usernamePassword"
#
#   kubectl annotate secret github-credentials -n oms-cicd \
#     "jenkins.io/credentials-description=GitHub access for saddle-oms repo"

# --- Docker Hub Credentials (for image push) ---
# Used by Jenkinsfile to push Docker images.
#
# Create:
#   kubectl create secret generic dockerhub-credentials \
#     -n oms-cicd \
#     --from-literal=username=<dockerhub-username> \
#     --from-literal=password=<dockerhub-access-token>

# --- Kubeconfig ---
# The DOKS cluster kubeconfig file.
# File: k8s-1-28-6-do-0-ams3-1713552913551-kubeconfig.yaml
# Cluster: https://49ff9492-c3f8-49f3-a2cc-eaa7c8e85908.k8s.ondigitalocean.com
# Namespace: oms-cicd
