apiVersion: v1
kind: Service
metadata:
  name: {{ include "oms-nest.fullname" . }}-frontend
  labels:
    {{- include "oms-nest.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oms-nest.frontend.selectorLabels" . | nindent 4 }}
