{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oms-nest.fullname" . }}
  labels:
    {{- include "oms-nest.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.frontend.host }}
        - {{ .Values.ingress.backend.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "oms-nest.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
    - host: {{ .Values.ingress.backend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "oms-nest.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
