{{/*
  GHCR registry credentials.

  The imagePullSecret "ghcr-credentials" must be created manually in each namespace:

    kubectl create secret docker-registry ghcr-credentials \
      --docker-server=ghcr.io \
      --docker-username=<github-username> \
      --docker-password=<github-pat> \
      --docker-email=<email> \
      -n oms-nest-staging

    kubectl create secret docker-registry ghcr-credentials \
      --docker-server=ghcr.io \
      --docker-username=<github-username> \
      --docker-password=<github-pat> \
      --docker-email=<email> \
      -n oms-nest-production
*/}}
